// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:144b40f1-80f5-4e44-b601-b9beb5fe8db1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JUROw4bAA",
    "aws_user_pools_web_client_id": "6uapf8nlmmhmuf8t18mgstu5ut",
    "oauth": {},
    "aws_user_files_s3_bucket": "echolocator-staging-profiles-staging",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "echolocatorStagingApi",
            "endpoint": "https://zbg2hyg4yc.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
