/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:682aa390-c5fd-4633-9cde-362a6e08e5a8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yn6F1FG3u",
    "aws_user_pools_web_client_id": "6ohc0s5v7vlj0fjp93tl6l25m1",
    "oauth": {},
    "aws_user_files_s3_bucket": "echolocator-staging-profiles122738-staging",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "echolocatorStagingApi",
            "endpoint": "https://akk8p5k8o0.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
