# Generated by Django 3.2.13 on 2022-05-31 01:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100)),
                ('town_area', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(max_length=5, unique=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('ecc', models.BooleanField(default=False)),
                ('violentcrime_quintile', models.FloatField(null=True)),
                ('zviolentcrimeflip', models.FloatField()),
                ('crime_percentile', models.FloatField()),
                ('education_percentile_quintile', models.FloatField()),
                ('education_percentile', models.FloatField()),
                ('house_number_symbol', models.IntegerField()),
                ('lat_lon_category', models.IntegerField()),
                ('max_rent_0br', models.FloatField()),
                ('max_rent_1br', models.FloatField()),
                ('max_rent_2br', models.FloatField()),
                ('max_rent_3br', models.FloatField()),
                ('max_rent_4br', models.FloatField()),
                ('max_rent_5br', models.FloatField()),
                ('max_rent_6br', models.FloatField()),
                ('school_choice', models.BooleanField(default=False)),
                ('total_mapc', models.FloatField()),
                ('town_website_description', models.TextField(blank=True)),
                ('town_link', models.URLField(blank=True, max_length=400)),
                ('wikipedia', models.TextField(blank=True)),
                ('wikipedia_link', models.URLField(blank=True, max_length=400)),
                ('street', models.URLField(blank=True, max_length=400)),
                ('school', models.URLField(blank=True, max_length=400)),
                ('town_square', models.URLField(blank=True, max_length=400)),
                ('open_space_or_landmark', models.URLField(blank=True, max_length=400)),
                ('street_thumbnail', models.URLField(blank=True, max_length=400)),
                ('school_thumbnail', models.URLField(blank=True, max_length=400)),
                ('town_square_thumbnail', models.URLField(blank=True, max_length=400)),
                ('open_space_or_landmark_thumbnail', models.URLField(blank=True, max_length=400)),
                ('street_license', models.CharField(blank=True, max_length=50)),
                ('school_license', models.CharField(blank=True, max_length=50)),
                ('town_square_license', models.CharField(blank=True, max_length=50)),
                ('open_space_or_landmark_license', models.CharField(blank=True, max_length=50)),
                ('street_license_url', models.URLField(blank=True, max_length=400)),
                ('school_license_url', models.URLField(blank=True, max_length=400)),
                ('town_square_license_url', models.URLField(blank=True, max_length=400)),
                ('open_space_or_landmark_license_url', models.URLField(blank=True, max_length=400)),
                ('street_description', models.TextField(blank=True)),
                ('school_description', models.TextField(blank=True)),
                ('town_square_description', models.TextField(blank=True)),
                ('open_space_or_landmark_description', models.TextField(blank=True)),
                ('street_artist', models.CharField(blank=True, max_length=400)),
                ('school_artist', models.CharField(blank=True, max_length=400)),
                ('town_square_artist', models.CharField(blank=True, max_length=400)),
                ('open_space_or_landmark_artist', models.CharField(blank=True, max_length=400)),
                ('street_username', models.CharField(blank=True, max_length=50)),
                ('school_username', models.CharField(blank=True, max_length=50)),
                ('town_square_username', models.CharField(blank=True, max_length=50)),
                ('open_space_or_landmark_username', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['zipcode'],
            },
        ),
    ]
