# Generated by Django 3.2.13 on 2022-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='zviolentcrimeflip',
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='crime_percentile',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_0br',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_1br',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_2br',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_3br',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_4br',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_5br',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='max_rent_6br',
            field=models.FloatField(null=True),
        ),
    ]
