# Generated by Django 5.2 on 2025-08-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_neighborhood_image_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="family_move_count",
            field=models.IntegerField(
                default=0,
                help_text="Total count of voucher holder families that have moved to neighborhood.",
            ),
        ),
    ]
