# Generated by Django 5.2 on 2025-08-22 15:56

import api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_neighborhood_move_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighborhood",
            name="open_space_or_landmark_thumbnail",
        ),
        migrations.RemoveField(
            model_name="neighborhood",
            name="school_thumbnail",
        ),
        migrations.RemoveField(
            model_name="neighborhood",
            name="street_thumbnail",
        ),
        migrations.RemoveField(
            model_name="neighborhood",
            name="town_square_thumbnail",
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="open_space_or_landmark_image",
            field=models.ImageField(
                blank=True,
                help_text="Save and return to this record to see uploaded image. Image will be displayed at 16/9 aspect ratio, 640x360.",
                storage=api.storage_backends.NeighborhoodPhotoStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="school_image",
            field=models.ImageField(
                blank=True,
                help_text="Save and return to this record to see uploaded image. Image will be displayed at 16/9 aspect ratio, 640x360.",
                storage=api.storage_backends.NeighborhoodPhotoStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="street_image",
            field=models.ImageField(
                blank=True,
                help_text="Save and return to this record to see uploaded image. Image will be displayed at 16/9 aspect ratio, 640x360.",
                storage=api.storage_backends.NeighborhoodPhotoStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="town_square_image",
            field=models.ImageField(
                blank=True,
                help_text="Save and return to this record to see uploaded image. Image will be displayed at 16/9 aspect ratio, 640x360.",
                storage=api.storage_backends.NeighborhoodPhotoStorage(),
                upload_to="",
            ),
        ),
    ]
