# Generated by Django 5.2 on 2025-09-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_neighborhood_thumbnail_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="region",
            field=models.CharField(
                blank=True,
                null=True,
                help_text="Informal geographic neighborhood groupings. Used for frontend filtering.",
                max_length=100,
            ),
        ),
    ]
