# Generated by Django 5.2.11 on 2026-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_region_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neighborhood",
            name="house_number_symbol",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="total_mapc",
            field=models.FloatField(null=True),
        ),
    ]
