// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dce8c557-d1ee-412c-aa01-cb0ffee07190",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cMMWUNuiJ",
    "aws_user_pools_web_client_id": "7h7b3jfo39b8g7fi9j6qvbmhqj",
    "aws_user_files_s3_bucket": "echolocator",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
