// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c169ccb8-0dc3-4102-9e80-230cfdc1bb1b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XXYSEULPo",
    "aws_user_pools_web_client_id": "3lqegeebm6na1e6fqicferpid4",
    "aws_user_files_s3_bucket": "echolocator",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_mobile_analytics_app_id": "87e9110a9e2a466d9c827eaefa816834",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
