// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0462cd2b-daff-448d-9933-84e23614679f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fmUkTpTzT",
    "aws_user_pools_web_client_id": "366viqdp9p1d4frltl4n5nm554",
    "oauth": {},
    "aws_user_files_s3_bucket": "echolocator-prod-profiles125932-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "echolocatorProdApi",
            "endpoint": "https://hsmw0hfp0c.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
