#!/bin/bash

set -e

if [[ -n "${ECHOLOCATOR_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Pull down secrets from S3.
"
}

function pull_env() {
    pushd "${DIR}"

    if aws s3 cp "s3://${ECHOLOCATOR_SETTINGS_BUCKET}/.env" ".env"; then
        echo "Updated environment variables file from ${ECHOLOCATOR_SETTINGS_BUCKET}"
    elif [[ ! -f ".env" ]]; then
        cp .env.sample .env
        echo "Updated environment variables file from .env.sample"
    fi

    popd
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pull_env
    fi
fi
