#!/bin/bash

set -e

if [[ -n "${ECHOLOCATOR_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Pull down secrets from S3.
"
}

# TODO: potentially as a part of this issue: https://github.com/azavea/echo-locator/issues/376
# after switching to a different bundler, we may want to copy and populate some env vars
function pull_env() {
    pushd "${DIR}"

    echo "Pulling .env from ${1}"
    # aws s3 cp "s3://${1}/.env" ".env"

    popd
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        pull_env
    fi
fi
