#!/bin/bash

USAGE="Build application for staging or a release."

source ./scripts/_sourced
check_for_help_flag "$@"

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

echo "Running update script"
REACT_APP_GIT_COMMIT="${GIT_COMMIT}" \
    ./scripts/update

echo "Building app static bundle"
./scripts/yarn run build

echo "Building Django"
# Build tagged container images
GIT_COMMIT="${GIT_COMMIT}" docker compose \
    -f docker-compose.yml \
    -f docker-compose.ci.yml \
    build django

echo "Bringing up PostgreSQL for Django tests"
docker compose up -d database

echo "Running tests"
GIT_COMMIT="${GIT_COMMIT}" \
    ./scripts/test
