#!/bin/bash

USAGE="Build application for staging or a release."

source ./scripts/_sourced
check_for_help_flag "$@"

echo "Running update script"
VITE_APP_GIT_COMMIT="${GIT_COMMIT}" \
    ./scripts/update

echo "Building Django"
# Build tagged Django container image
# This will rebuild the 'django' image, which now contains the static files.
GIT_COMMIT="${GIT_COMMIT}" docker compose \
    -f docker-compose.yml \
    -f docker-compose.ci.yml \
    build django

echo "Bringing up PostgreSQL for Django tests"
docker compose up -d database

echo "Running tests"
GIT_COMMIT="${GIT_COMMIT}" \
    ./scripts/test
