#!/bin/bash

USAGE="Publish neighborhood thumbnail images."

source ./scripts/_sourced
check_for_help_flag "$@"


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" != "staging" ] && [ "${1:-}" != "production" ]
        then
            echo "ERROR: Unrecognized environment ${1}. Should be 'staging' or 'production'."
            exit 1
    else
        TAUI_SITE_BUCKET="s3://echo-locator-${1}-site-us-east-1"
        aws s3 cp --profile echo-locator --recursive --exclude "*.gitkeep" neighborhood_data/images/ "${TAUI_SITE_BUCKET}/assets/neighborhoods/"
    fi
fi
