#!/bin/bash

DIR="$(dirname "$0")"
USAGE="Execute Terraform subcommands with remote state management."

source ./scripts/_sourced
check_for_help_flag "$@"

TERRAFORM_DIR="${DIR}/../deployment/terraform"
    echo
    echo "Attempting to deploy application version [${GIT_COMMIT}]..."
    echo "-----------------------------------------------------"
    echo

if [[ -n "${ECHOLOCATOR_SETTINGS_BUCKET}" ]]; then
    pushd "${TERRAFORM_DIR}"

    aws s3 cp "s3://${ECHOLOCATOR_SETTINGS_BUCKET}/terraform/terraform.tfvars" \
                "${ECHOLOCATOR_SETTINGS_BUCKET}.tfvars"

    case "${1}" in
        plan)
            # Clear stale modules & remote state, then re-initialize
            rm -rf .terraform terraform.tfstate*
            terraform init \
                -backend-config="bucket=${ECHOLOCATOR_SETTINGS_BUCKET}" \
                -backend-config="key=terraform/state"

            terraform plan \
                -var="image_tag=${GIT_COMMIT}" \
                -var-file="${ECHOLOCATOR_SETTINGS_BUCKET}.tfvars" \
                -out="${ECHOLOCATOR_SETTINGS_BUCKET}.tfplan"
            ;;
        apply)
            terraform apply "${ECHOLOCATOR_SETTINGS_BUCKET}.tfplan"
            ;;
        *)
            echo "ERROR: I don't have support for that Terraform subcommand!"
            exit 1
            ;;
    esac

    popd
else
    echo "ERROR: No ECHOLOCATOR_SETTINGS_BUCKET variable defined."
    exit 1
fi
