#!/bin/bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Reset database.
"
}

function reset_db() {
    ./scripts/manage reset_db
    ./scripts/manage migrate
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        reset_db
    fi
fi
