#!/bin/bash

set -e

if [[ -n "${ECHOLOCATOR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Starts servers using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        AWS_PROFILE=echo-locator docker-compose up
    fi
fi
