#!/bin/bash

USAGE="Run linters and tests."

source ./scripts/_sourced
check_for_help_flag "$@"

if [ "$(whoami)" == "runner" ]; then
    echo "Running Django tests..."
    GIT_COMMIT="${GIT_COMMIT}" docker compose \
        -f docker-compose.yml \
        -f docker-compose.ci.yml \
        run --rm --no-deps --entrypoint python \
        django \
        manage.py test
else
    # Pylint has overlap with flake8,
    # if causing trouble just turn off in linter and CI linter
    # see PR 455
    echo "Checking Django formatting and linting using GH Super-Linter..."
    docker run --rm \
        -e RUN_LOCAL=true \
        --env-file ".github/super-linter.env" \
        -v $PWD:/tmp/lint github/super-linter:v4

    echo "Running Django tests..."
    ./scripts/manage test
fi
