#!/bin/bash

set -e

if [[ -n "${ECHOLOCATOR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Run linters and tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        echo "Checking Django formatting and linting using GH Super-Linter..."
        docker run --rm \
            -e RUN_LOCAL=true \
            -e VALIDATE_ALL_CODEBASE=false \
            -e IGNORE_GITIGNORED_FILES=true \
            -e FILTER_REGEX_INCLUDE="src/backend/" \
            -e FILTER_REGEX_EXCLUDE=".*(migrations/*|manage.py).*" \
            -e LINTER_RULES_PATH="/" \
            -e PYTHON_BLACK_CONFIG_FILE="src/backend/pyproject.toml" \
            -e PYTHON_FLAKE8_CONFIG_FILE="src/backend/setup.cfg" \
            -e VALIDATE_PYTHON_ISORT=false \
            -v $PWD:/tmp/lint github/super-linter:slim-latest

        echo "Running Taui tests..."
        docker-compose run --rm taui test
    fi
fi
