#!/bin/bash

set -e

if [[ -n "${ECHOLOCATOR_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images and execute database migrations.
"
}

function cleanup() {
    docker-compose stop
}

trap cleanup ERR

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Build app container image first
        docker-compose \
            -f docker-compose.yml \
            build app

        # Install frontend NPM modules
        docker-compose \
            -f docker-compose.yml \
            run --rm --no-deps app \
            yarn install

        # Build static asset bundle for React frontend
        # Separated to build app static assets before copied to django container
        docker-compose \
            -f docker-compose.yml \
            run --rm --no-deps app \
            yarn run build

        # Build django and db container images
        docker-compose build database django

        # Bring up PostgreSQL and Django in a way that respects
        # configured service health checks.
        docker-compose up -d database django

        # Apply any outstanding Django migrations
        ./scripts/manage migrate

        # Collect Django static files
        ./scripts/manage collectstatic --no-input

        # Add group permissions
        ./scripts/manage loaddata users/fixtures/group_permissions
        
        docker-compose stop
    fi
fi
