name: CI

on:
  push:
    branches:
      - develop
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/test/')

      - run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm terraform -c "
            unset AWS_PROFILE
            ./scripts/infra plan
            ./scripts/infra apply
          "
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/test/')
        env:
          ECHOLOCATOR_SETTINGS_BUCKET: echo-locator-stgdjango-config-us-east-1
