name: CI

on:
  push:
    branches:
      - develop
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - run: ./scripts/bootstrap
        if: github.ref != 'refs/heads/master'
        env:
          ECHOLOCATOR_SETTINGS_BUCKET: echo-locator-stgdjango-config-us-east-1

      - run: ./scripts/cibuild

      ################################
      # Run GH Super-Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          FILTER_REGEX_INCLUDE: src/backend/
          FILTER_REGEX_EXCLUDE: .*(migrations/*|manage.py).*
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: src/backend/pyproject.toml
          PYTHON_FLAKE8_CONFIG_FILE: src/backend/setup.cfg
          VALIDATE_GITLEAKS: false
          VALIDATE_JSCPD: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JSON: false

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/test/')

      - run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm terraform -c "
            unset AWS_PROFILE
            ./scripts/infra plan
            ./scripts/infra apply
          "
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/test/')
        env:
          ECHOLOCATOR_SETTINGS_BUCKET: echo-locator-stgdjango-config-us-east-1
