# Generated by Django 3.2.12 on 2022-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commute_priority',
            field=models.CharField(choices=[('NI', 'Not important'), ('SI', 'Somewhat important'), ('I', 'Important'), ('VI', 'Very important')], default='NI', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desired_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_safety_priority',
            field=models.CharField(choices=[('NI', 'Not important'), ('SI', 'Somewhat important'), ('I', 'Important'), ('VI', 'Very important')], default='SI', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_quality_priority',
            field=models.CharField(choices=[('NI', 'Not important'), ('SI', 'Somewhat important'), ('I', 'Important'), ('VI', 'Very important')], default='NI', max_length=18),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_mode',
            field=models.CharField(choices=[('CAR', 'car'), ('BT', 'bus/train'), ('BTE', 'bus/train/express')], default='BT', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.EmailField(default='email@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voucher_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
