# Generated by Django 3.2.12 on 2022-04-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('purpose', models.CharField(choices=[('WK', 'Work'), ('DC', 'Day care'), ('FA', 'Family'), ('FR', 'Friends'), ('WP', 'Worship'), ('DR', 'Doctor'), ('OT', 'Other')], default='WK', max_length=8)),
                ('primary_destination', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
