# Generated by Django 3.2.13 on 2022-05-12 21:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-71.06, 42.36, srid=4326), help_text='The lat/lng point location of the destination', srid=4326),
        ),
    ]
