# Generated by Django 3.2.13 on 2022-05-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='users.userprofile'),
        ),
    ]
