# Generated by Django 3.2.13 on 2022-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_destination_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='purpose',
            field=models.CharField(choices=[('WK', 'Work'), ('DC', 'Daycare'), ('FA', 'Family'), ('FR', 'Friends'), ('WP', 'Worship'), ('DR', 'Doctor'), ('OT', 'Other')], default='WK', max_length=2),
        ),
    ]
