# Generated by Django 3.2.13 on 2022-05-13 18:27

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_destination_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='address',
            new_name='label',
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-71.06, 42.36, srid=4326), help_text='The lat/lng point location of the destination', srid=4326),
        ),
    ]
