# Generated by Django 3.2.13 on 2022-05-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_destination_purpose'),
        ('users', '0005_update_destination_fields'),
    ]

    operations = [
    ]
