# Generated by Django 3.2.13 on 2022-06-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='voucher_number',
        ),
    ]
