# Generated by Django 3.2.13 on 2022-06-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_voucher',
            field=models.BooleanField(default=True),
        ),
    ]
