# Generated by Django 3.2.13 on 2022-06-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_has_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='has_voucher',
            field=models.BooleanField(default=True, verbose_name='Has Boston Housing Authority voucher'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voucher_bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Boston Housing Authority voucher bedrooms'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Boston Housing Authority voucher number'),
        ),
    ]
