# Generated by Django 5.2 on 2025-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_make_usernames_lowercase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("WK", "Work"),
                    ("DC", "Daycare"),
                    ("FA", "Family"),
                    ("FR", "Friends"),
                    ("WP", "Worship"),
                    ("DR", "Doctor"),
                    ("OT", "Other"),
                    ("SC", "School"),
                ],
                default="WK",
                max_length=2,
            ),
        ),
    ]
